# Generated by Django 2.0.7 on 2018-08-08 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LIFE COACHING', 'Life Coaching'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('feature', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5, verbose_name='Featured?')),
                ('user_post', models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
