# Generated by Django 2.0.7 on 2018-08-09 18:16

from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmazingQuotesAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(verbose_name='About Amazing Quotes')),
                ('phone_no', models.CharField(default='0712626160', max_length=20)),
                ('email', models.EmailField(default='amazingquotes@gmail.com', max_length=254)),
                ('address', models.CharField(default='Dar es Salaam', max_length=128, verbose_name='Address')),
                ('facebook', models.URLField(default='https://facebook.com/amazingquotes', max_length=128, verbose_name='Facebook link')),
                ('instagram', models.URLField(default='https://insta.com/amazingquotes', max_length=128, verbose_name='Instagram link')),
                ('twitter', models.URLField(default='https://twitter.com/amazingquotes', max_length=128, verbose_name='Twitter link')),
                ('linkedin', models.CharField(default='https://linkedin.com/amazingquotes', max_length=128, verbose_name='Linkedin link')),
            ],
            options={
                'verbose_name': 'About Amazing Quotes',
                'verbose_name_plural': 'About Amazing Quotes',
            },
        ),
        migrations.CreateModel(
            name='ContactRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='From')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phoneno', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type_of_event', models.CharField(max_length=128)),
                ('time', models.DateTimeField(verbose_name='Date and Time')),
                ('city', models.CharField(max_length=128, verbose_name='City')),
                ('location', models.CharField(max_length=64, verbose_name='Location')),
                ('price', models.IntegerField(default=0, verbose_name='Price (0 if free)')),
                ('description', models.TextField(default='This is one of our events you will never forget.', verbose_name='About event')),
                ('video_url', models.URLField(blank=True, default='https://www.youtube.com/watch?v=SQVpx1LFloI&t=79s', verbose_name='Video')),
                ('image', models.ImageField(default='media/Albert-Einstein-Quote-About-Life-Wallpaper.png', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='events', verbose_name='Event Poster')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_registrar', models.CharField(default='Attendee', max_length=128)),
                ('email_of_registrar', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15)),
                ('name_of_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrar', to='amazingQuote.Event')),
            ],
            options={
                'verbose_name': 'Registered Attendee',
                'verbose_name_plural': 'Registered Attendees',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of The person Ordering')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone number')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of Product')),
                ('quantity', models.IntegerField(verbose_name='Quantity available')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('type_of_product', models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BOOK', 'Book'), ('CUP', 'Cup'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type')),
                ('feature', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='The quote')),
                ('writer', models.CharField(max_length=64, verbose_name='Quote by')),
                ('quote_image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='quotes', verbose_name='Quote Image')),
                ('date_of_publish', models.DateField(unique=True, verbose_name='Date to be published')),
            ],
            options={
                'verbose_name': 'Quote of the Day',
                'verbose_name_plural': 'Daily quotes',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name of Team member')),
                ('title', models.CharField(max_length=64, verbose_name='Position')),
                ('about', models.TextField(verbose_name='About You')),
                ('image', models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='team', verbose_name='Profile image')),
                ('email', models.EmailField(default='amazingquotes@gmail.com', max_length=254, verbose_name='Email')),
                ('phone_no', models.CharField(default='+255712626160', max_length=15)),
                ('speaker', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5)),
            ],
            options={
                'verbose_name': 'Team Member',
                'verbose_name_plural': 'Team Members',
            },
        ),
        migrations.CreateModel(
            name='TrainingTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.CharField(choices=[('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('RELATIONSHIP', 'Relationship')], default='LIFE COACHING', max_length=20)),
                ('description', models.TextField()),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='amazingQuote.TeamMember')),
            ],
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Value', max_length=128)),
                ('description', models.TextField(max_length=256, verbose_name='Value Description')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='amazingQuote.AmazingQuotesAbout')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='amazingQuote.Product'),
        ),
    ]
