# Generated by Django 2.0.7 on 2018-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuote', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sliderimages',
            name='height',
        ),
        migrations.RemoveField(
            model_name='sliderimages',
            name='width',
        ),
        migrations.AlterField(
            model_name='sliderimages',
            name='slider_image',
            field=models.ImageField(upload_to='Slider Images', verbose_name='Slider Image'),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('RELATIONSHIP', 'Relationship')], default='LIFE COACHING', max_length=20),
        ),
    ]
