# Generated by Django 2.0.7 on 2018-09-09 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuote', '0002_auto_20180908_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('CUP', 'Cup'), ('BOOK', 'Book')], max_length=64, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='speaker',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='category',
            field=models.CharField(choices=[('LIFE COACHING', 'Life Coaching'), ('LEADERSHIP', 'Leadership'), ('RELATIONSHIP', 'Relationship'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='LIFE COACHING', max_length=20),
        ),
    ]
