# Generated by Django 2.0.7 on 2018-08-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuote', '0002_auto_20180810_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image_url',
            field=models.CharField(auto_created=True, blank=True, default='Dont edit this field', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_url',
            field=models.CharField(auto_created=True, blank=True, default='Dont edit this field', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='image_url',
            field=models.CharField(auto_created=True, blank=True, default='Dont edit this field', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BOOK', 'Book'), ('BAND', 'Wrist band'), ('TSHIRT', 'T-shirt')], max_length=64, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='speaker',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5),
        ),
        migrations.AlterField(
            model_name='trainingtopic',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('RELATIONSHIP', 'Relationship'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='LIFE COACHING', max_length=20),
        ),
    ]
