# Generated by Django 2.0.7 on 2018-09-14 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(auto_created=True, blank=True, default='Dont edit this field', max_length=128, null=True)),
                ('title', models.CharField(max_length=128)),
                ('category', models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('LIFE COACHING', 'Life Coaching'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LEADERSHIP', 'Leadership')], default='LIFE', max_length=64, verbose_name='Post Category')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_posts')),
                ('feature', models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=5, verbose_name='Featured?')),
                ('user_post', models.ForeignKey(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
