# Generated by Django 2.0.7 on 2018-09-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
