# Generated by Django 2.0.7 on 2018-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('LEADERSHIP', 'Leadership'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LIFE', 'Life Coaching')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
