# Generated by Django 2.0.7 on 2018-08-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=5, verbose_name='Featured?'),
        ),
    ]
