# Generated by Django 2.0.7 on 2018-07-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LIFE', 'Life Coaching'), ('LEADERSHIP', 'Leadership'), ('RELATIONSHIP', 'Relationship'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
