# Generated by Django 2.0.7 on 2018-07-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180712_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LEADERSHIP', 'Leadership'), ('LIFE', 'Life Coaching'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
