# Generated by Django 2.0.7 on 2018-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180722_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('LEADERSHIP', 'Leadership'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LIFE COACHING', 'Life Coaching')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
