# Generated by Django 2.0.7 on 2018-07-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20180722_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('RELATIONSHIP', 'Relationship'), ('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
