# Generated by Django 2.0.7 on 2018-07-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20180723_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('LIFE COACHING', 'Life Coaching'), ('RELATIONSHIP', 'Relationship'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
