# Generated by Django 2.0.7 on 2018-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20180724_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LEADERSHIP', 'Leadership'), ('RELATIONSHIP', 'Relationship'), ('LIFE COACHING', 'Life Coaching')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
