# Generated by Django 2.0.7 on 2018-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20180724_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5),
        ),
    ]
