# Generated by Django 2.0.7 on 2018-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20180726_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='NO', max_length=5, verbose_name='Featured?'),
        ),
    ]
