# Generated by Django 2.0.7 on 2018-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20180726_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LIFE COACHING', 'Life Coaching'), ('LEADERSHIP', 'Leadership'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='NO', max_length=5, verbose_name='Featured?'),
        ),
    ]
