# Generated by Django 2.0.7 on 2018-07-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20180726_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('LEADERSHIP', 'Leadership'), ('ENTREPRENEURSHIP', 'Entrepreneurship'), ('LIFE COACHING', 'Life Coaching'), ('RELATIONSHIP', 'Relationship')], default='LIFE', max_length=64, verbose_name='Post Category'),
        ),
    ]
