# Generated by Django 2.0.7 on 2018-07-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BAND', 'Wrist band'), ('TSHIRT', 'T-shirt'), ('BOOK', 'Available')], max_length=64, verbose_name='Product Type'),
        ),
    ]
