# Generated by Django 2.0.7 on 2018-07-12 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0002_auto_20180712_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('BOOK', 'Available'), ('CUP', 'Cup')], max_length=64, verbose_name='Product Type'),
        ),
    ]
