# Generated by Django 2.0.6 on 2018-07-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0005_auto_20180717_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BOOK', 'Available'), ('BAND', 'Wrist band'), ('CUP', 'Cup')], max_length=64, verbose_name='Product Type'),
        ),
    ]
