# Generated by Django 2.0.6 on 2018-07-20 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0006_auto_20180719_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BAND', 'Wrist band'), ('BOOK', 'Available'), ('TSHIRT', 'T-shirt')], max_length=64, verbose_name='Product Type'),
        ),
    ]
