# Generated by Django 2.0.6 on 2018-07-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0007_auto_20180720_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='From')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phoneno', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('message', models.TextField(verbose_name='Message')),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BAND', 'Wrist band'), ('TSHIRT', 'T-shirt'), ('BOOK', 'Available')], max_length=64, verbose_name='Product Type'),
        ),
    ]
