# Generated by Django 2.0.6 on 2018-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0008_auto_20180721_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazingquotesabout',
            name='address',
            field=models.CharField(default='Dar es Salaam', max_length=128, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BOOK', 'Available'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('CUP', 'Cup')], max_length=64, verbose_name='Product Type'),
        ),
    ]
