# Generated by Django 2.0.6 on 2018-07-22 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0009_auto_20180721_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(default='This is one of our events you will never forget.', verbose_name='About event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Price (0 if free)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BOOK', 'Available'), ('TSHIRT', 'T-shirt'), ('CUP', 'Cup'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
    ]
