# Generated by Django 2.0.6 on 2018-07-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0010_auto_20180722_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(default='https://www.youtube.com/watch?v=SQVpx1LFloI&t=79s', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BOOK', 'Available'), ('BAND', 'Wrist band'), ('TSHIRT', 'T-shirt')], max_length=64, verbose_name='Product Type'),
        ),
    ]
