# Generated by Django 2.0.7 on 2018-07-22 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0011_auto_20180722_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='media/Albert-Einstein-Quote-About-Life-Wallpaper.png', upload_to='', verbose_name='Event Poster'),
        ),
        migrations.AlterField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, default='https://www.youtube.com/watch?v=SQVpx1LFloI&t=79s', verbose_name='Video'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BOOK', 'Available'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('CUP', 'Cup')], max_length=64, verbose_name='Product Type'),
        ),
    ]
