# Generated by Django 2.0.7 on 2018-07-22 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0012_auto_20180722_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='email',
            field=models.EmailField(default='amazingquotes@gmail.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='teammember',
            name='phone_no',
            field=models.CharField(default='+255712626160', max_length=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BOOK', 'Available'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
    ]
