# Generated by Django 2.0.7 on 2018-07-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0013_auto_20180722_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('BOOK', 'Available')], max_length=64, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='phone_no',
            field=models.CharField(default='+255712626160', max_length=15),
        ),
    ]
