# Generated by Django 2.0.7 on 2018-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0014_auto_20180722_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('CUP', 'Cup'), ('BOOK', 'Available')], max_length=64, verbose_name='Product Type'),
        ),
    ]
