# Generated by Django 2.0.7 on 2018-07-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0015_auto_20180722_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BAND', 'Wrist band'), ('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BOOK', 'Available')], max_length=64, verbose_name='Product Type'),
        ),
    ]
