# Generated by Django 2.0.7 on 2018-07-23 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0016_auto_20180722_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='Value', max_length=128)),
                ('description', models.TextField(verbose_name='Value Description')),
                ('about', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='amazingQuotes.AmazingQuotesAbout')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('BOOK', 'Book')], max_length=64, verbose_name='Product Type'),
        ),
    ]
