# Generated by Django 2.0.7 on 2018-07-24 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0018_auto_20180723_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of The person Ordering')),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=15, verbose_name='Phone number')),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BAND', 'Wrist band'), ('TSHIRT', 'T-shirt'), ('CUP', 'Cup'), ('BOOK', 'Book')], max_length=64, verbose_name='Product Type'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='amazingQuotes.Product'),
        ),
    ]
