# Generated by Django 2.0.7 on 2018-07-24 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0019_auto_20180724_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BOOK', 'Book'), ('CUP', 'Cup'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
    ]
