# Generated by Django 2.0.7 on 2018-07-24 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0020_auto_20180724_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='amazingQuotes.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BOOK', 'Book'), ('TSHIRT', 'T-shirt'), ('CUP', 'Cup'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
    ]
