# Generated by Django 2.0.7 on 2018-07-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0021_auto_20180724_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('BOOK', 'Book')], max_length=64, verbose_name='Product Type'),
        ),
    ]
