# Generated by Django 2.0.7 on 2018-07-26 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0023_auto_20180726_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='The quote')),
                ('writer', models.CharField(max_length=64, verbose_name='Quote by')),
                ('quote_image', models.ImageField(upload_to='', verbose_name='Quote Image')),
                ('date', models.DateField(unique_for_date=True, verbose_name='Date to be published')),
            ],
            options={
                'verbose_name': 'Quote of the Day',
                'verbose_name_plural': 'Daily quotes',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('TSHIRT', 'T-shirt'), ('BOOK', 'Book'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
    ]
