# Generated by Django 2.0.7 on 2018-07-26 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0025_auto_20180726_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='date',
            new_name='date_of_publish',
        ),
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('NO', 'No'), ('YES', 'Yes')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('CUP', 'Cup'), ('BAND', 'Wrist band'), ('BOOK', 'Book'), ('TSHIRT', 'T-shirt')], max_length=64, verbose_name='Product Type'),
        ),
    ]
