# Generated by Django 2.0.7 on 2018-07-26 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0026_auto_20180726_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='feature',
            field=models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], default='YES', max_length=10, verbose_name='Is it Featured?'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('BOOK', 'Book'), ('TSHIRT', 'T-shirt'), ('BAND', 'Wrist band'), ('CUP', 'Cup')], max_length=64, verbose_name='Product Type'),
        ),
    ]
