# Generated by Django 2.0.7 on 2018-07-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amazingQuotes', '0027_auto_20180726_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type_of_product',
            field=models.CharField(choices=[('TSHIRT', 'T-shirt'), ('BOOK', 'Book'), ('CUP', 'Cup'), ('BAND', 'Wrist band')], max_length=64, verbose_name='Product Type'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='date_of_publish',
            field=models.DateField(unique=True, verbose_name='Date to be published'),
        ),
    ]
